export const SHOW_WIPGETS = "SHOW_WIPGETS";
export const SHOW_BANNERS = "SHOW_BANNERS";
export const SHOW_CATEGORYPRODUCTS = "SHOW_CATEGORYPRODUCTS";
export const SHOW_SEARCHPRODUCT = "SHOW_SEARCHPRODUCT";
export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
export const SHOW_MOREPRODUCTS = "SHOW_MOREPRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
