export const SHOW_WIPGETS = "SHOW_WIPGETS";
export const SHOW_BANNERS = "SHOW_BANNERS";
export const SHOW_CATEGORYPRODUCTS = "SHOW_CATEGORYPRODUCTS";
export const SHOW_SEARCHPRODUCT = "SHOW_SEARCHPRODUCT";
export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
